sonar.organization=your-org
sonar.projectKey=your-org_pacx
sonar.projectName=PACX
sonar.language=cs
sonar.sourceEncoding=UTF-8
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.coverage.exclusions=**/*Test*.cs,**/obj/**
sonar.exclusions=**/*.g.cs
