name: Dependency Metadata
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  metadata:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required to label dependency PRs.
    steps:
      - uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2
        id: metadata
      - name: Label dependency PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          UPDATE_TYPE: ${{ steps.metadata.outputs.update-type }}
        run: |
          gh pr edit "$PR_NUMBER" \
            --add-label "dependencies,$UPDATE_TYPE"
